apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv
spec:
  storageClassName: manual
  hostPath:
    path: "/data/influx-pv"
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce