apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            name: nginx-pod
            labels:
                app: nginx
        spec:
            containers:
            -   name: nginx-cnt
                env:
                    - name: IP
                      valueFrom:
                          configMapKeyRef:
                              name: service-ip
                              key: IP
                livenessProbe:
                    httpGet:
                        path: /
                        port: 80
                    initialDelaySeconds: 15
                image: nginx
                imagePullPolicy: Never
                command: [ "ash" ]
                args: [ "run_nginx.sh" ]
                ports:
                -   name: http
                    containerPort: 80
                -   name: https
                    containerPort: 443
                -   name: ssh
                    containerPort: 22
            restartPolicy: Always