apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: pma
  ports:
  - name: pma
    port: 5000
  type: LoadBalancer