apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: wordpress
  ports:
  - name: wp
    port: 5050
  type: LoadBalancer